nglviewer/ngl

build/includes/embedded-dev.json, build/notes.txt
Uses non-minified NGL code to aid debugging.
=> Adding embedded-dev build target

examples/js/examples.js, src/surface/marching-cubes.js
Small change to marching cubes - Also updated the "avSurf" example as demo.
The marching cubes implementation always generates integer `mu` for EDT Surfaces, so safe to use as an index, but with AV Surfaces it was creating non-integer indexes into `atomindex` array.
=> Fixes atom-based colouring of 'av' surfaces

src/controls/trackball-controls.js
Inspects event.deltaMode to decide if deltaY is in lines or pixels
Looking upstream the code has changed:
https://github.com/mrdoob/three.js/commit/93721d3246773ce88bc1c0183e2ff954e4b0f18b
But their example is broken for me on Chrome and IE (works on Firefox):
https://threejs.org/examples/#misc_controls_trackball
I'll add an issue on the three.js issue tracker but this fixes it for me on FF 49, Chrome 54 and IE 11 (all on Windows 7)
=> Fixes #233: Detect appropriate units for mousewheel zoom (for IE11)

src/surface/av-surface.js
Oops, somewhat embarrassing bug in surface generation - for example: 3pqr, av-style surface in current master renders about half of the surface correctly and the other half in a very broken way. I was (consistently) miscalculating cell indexes in AVHash and quite often they'd fall outside the relevant array. I think this fixes it, but you might want to test a few of your other favourite structures.
=> Indexing bug(s) in AVSurface

src/representation/molecularsurface-representation.js
I get slightly different surfaces in these two cases
1) Create a new surface representation with the filterSele supplied at creation time (green below)
2) Create a new surface representation with no filterSele and subsequently add it (red/brown below)
The green version is wrong I think - it doesn't include enough of the protein so draws protein surface where it isn't - this PR adds a small amount of padding (6.0A) when selecting which atoms to calculate surface on initially and fixes the first case (now looks like the second red/brown one).
=> Add some padding when selecting which atoms to use for filtered surfaces

CHANGELOG.md, examples/js/examples.js, src/buffer/contour-buffer.js, src/representation/surface-representation.js, src/surface/marching-cubes.js, src/surface/volume.js
As mentioned in #236. Added a contour option to volume surfaces that produces sparser meshes. I've also removed setAttribute method from the ContourBuffer class - I think this is redundant now (I've tested mol surfaces and volume surfaces with this removed, is there anything else that would use it?)
=> VolumeSurface contour display style

src/stage/stage.js
The current getRepresentationsByName function does not work for regular expressions.
The return value of typeof RegExp is object, so the function jumps into the else clause and tries to access a member repr of name which not exists and assigns undefined to reprName. In the following every representation is added to the list. An additional instanceof condition in the if statement should do the work.
=> bugfix for function getRepresentationsByName RegExp was not working

src/representation/contact-representation.js, src/representation/hyperball-representation.js
Two tiny typos analogous to #306: `bondData.color1` -> `bondData.color`
=> 2x 1-char fixes: color1 -> color

test/parser/tests-cif-parser.js, test/parser/tests-csv-parser.js, test/parser/tests-cube-parser.js, test/parser/tests-dcd-parser.js, test/parser/tests-dx-parser.js, test/parser/tests-dxbin-parser.js, test/parser/tests-gro-parser.js, test/parser/tests-json-parser.js, test/parser/tests-mmtf-parser.js, test/parser/tests-mol2-parser.js, test/parser/tests-mrc-parser.js, test/parser/tests-msgpack-parser.js, test/parser/tests-netcdf-parser.js, test/parser/tests-obj-parser.js, test/parser/tests-pdb-parser.js, test/parser/tests-ply-parser.js, test/parser/tests-pqr-parser.js, test/parser/tests-text-parser.js, test/parser/tests-xml-parser.js
I realised while writing tests for the SdfWriter that the parser tests weren't actually executing (I guess because Parser.parse changed to return a promise rather than accept a callback) this should re-enable them. 
One of the cif test fails - I've not fixed it as not sure what correct behaviour is, let me know and I can fix it
(Left out tests-sdf-writer.js as it would conflict with previous PR!)
=> Reinstating parser test code

package.json
Tiny PR - for some reason the expansion {*.vert,*.frag} in the "ts" script fails on both my ubuntu boxes (though it works fine on CentOS)
=> Remove bash-ism from package.json, (fixes build error on Ubuntu)

src/surface/molecular-surface.js
There's a small typo molecular-surface.js which results in all atoms having radius 1.0A for surface generation - changed it to use vdw. I haven't looked how this would work with custom radii.
=> Fix missing radii / odd surfaces

src/geometry/dash.ts, src/representation/angle-representation.js, src/representation/dihedral-representation.js
This fixes two bugs in the angle/dihedral representations
- Angle representation with an empty `structureView` threw error (`setVisibility` was trying to set attributes of buffers that had not been created)
- Missing lines in dihedral representation
- Incorrect final coordinates for dihedral dashed lines
It also adds a `getFixedLengthWrappedDashData` which wraps the dashes along a line/cylinder path and uses it in dihedral/angle represnetations . I've put this in as a new function as you wouldn't want this for interaction repr or the distance repr. It could be improved a little by only wrapping when one line section starts at the end of the previous one (and various other nice little touches like stretching over total length of continuous sections) but as it is it makes the angle and …
=> Small measurement fixes

src/viewer/gl-utils.ts
On IE11, if I load multiple structures (sometimes as few as 3) picking stops working for new structures.
I think I've tracked it down. IE11 does support reading pixels from/to a float buffer, or at least, on my hardware here it does, but the `testTextureSupport` method needed a small fix to work properly on IE (this mirrors what THREE.js does internally when creating the context object). 
If NGL thinks it can't read float values then it falls back to unsigned int, but when it comes to extracting the object ID from the pixel that's been read there's only one byte to represent object ID so only the first 256 objects can be picked!
=> Fix bug with texture support detection in IE11

src/chemistry/functional-groups.ts, src/chemistry/valence-model.ts, src/controls/mouse-actions.ts, src/structure/structure-utils.ts
Fixes the case of acetate anion (not detected as carboxylate) and incorrectly assigning positive charge to sulfonamide nitrogen
=> Carboxylate detection and sulfonamide protonation

src/shader/SDFFont.vert
The `fixedSize` labels are great, but they behave strangely in orthographic projection. (The perspective adjustment is still applied so the ones close to the camera are tiny and the ones far away are huge). This seems to fix it, though, as always, there may be a better way!
=> Fix for fixedSize labels in orthographic view

src/stage/stage.ts, src/viewer/viewer.ts
For this fix to work I had to add a wrapper div to canvas and annotations. Without this wrapper, we'd have to directly change the css positioning for the container provided by the user and this could lead to side effects for the user (e.g. if the user sets another positioning style for its container).
This fix doesn't solve the issue of annotations displayed outside of their container element.
=>  fix: relative css position for preventing bug in annotations #461

src/structure/structure-utils.ts
Noticed an issue with concatstructure dropping an atom's element as parsed from the input file, and I traced it to this difference between e.g the SDFParser. Could you look at the patch and let me know what else would be needed to merge the change?
Could be tested with the fluorine of https://www.rcsb.org/ligand/5SZ
Here's a codepen showing the fluorine is white as a result: https://codepen.io/anon/pen/bLPXrx?editors=0010
=> fix: concatstructure forgets element

src/structure/structure-utils.ts
new pull request after https://github.com/arose/ngl/pull/491
=> fix: concatstructure forgets altloc, occupancy, bfactor

src/polyfills.js
=> Polyfilling Number.(MAX|MIN)_SAFE_INTEGER to fix text on IE11

examples/scripts/representation/angle.js, examples/scripts/representation/dihedral.js, examples/scripts/representation/distance.js, src/representation/distance-representation.js, src/representation/measurement-representation.js
You can specify measurement parameters (`atomPair`, `atomTriple`, `atomQuad`) with either integer atom indices or string selection expressions. Selection expressions were/are evaluated in context of component's structureView, so automatically respect selection on component. 
This change ensures consistent behaviour when using integers to specify atoms for measurement representations.
=> FIX: Measurements defined with atom indices respect component selections

src/representation/dihedral-representation.js
This fixes the small bug in #458 changes to `planeVisible` didn't rebuild. Also adds a `extendLine` parameter. This defaults to true (displays as before), but if this is false the representation looks approximately like that requested by @giagitom in #458
(Apologies for the delay in doing this...)
=> Dihedral fix

src/representation/dihedral-representation.js
Fix for bug introduced in #503 (extendLines mode was still allocating arrays for the plane mesh)
=> Another dihedral fix

src/buffer/doublesided-buffer.ts, src/chemistry/interactions/contact.ts
This PR adresses a limitation with filterSele described in #517 
E.g.: when studying the contacts between an antigen and an antibody, you can set filterSele to the antigene. But you'll get contacts between the antibody and the antigene, as well as undesired contacts that are internal to the antibody.
In this proposal, filterSele can also be set as an Array. If that is the case, then the script will filter contacts keeping only those that are set between both selections.
=> Contacts: filterSele can be an array to filter contacts between 2 sets

src/surface/volume.ts
Workers don't get the polyfills applied so a call to Object.assign breaks in IE11. This fixes it (remove call to Object.assign) for those of us ~~unforunate~~ lucky enough to be still using IE11 ;)
=> IE11 fix in volume surface

src/structure/structure-utils.ts
When concatenating molecules, bonds get copied to the new `ResidueType`s in `assignResidueTypeBonds` - this fix ensures only bonds within a residue are copied. Without this, the bondgraph for the residue includes out-of-range atom indices, which confuses the ring-finding code. 
Example with fix:
http://fredludlow.com/ngl/concat-bond-fix/examples/webapp.html?script=test/concat
Example without fix:
http://fredludlow.com/ngl/pick-wider/examples/webapp.html?script=test/concat
The pi-pi interaction between PHE82 and HIS84 is not shown in the second example as the concatenated molecule's PHE ResidueType reports no rings.
=> Fix for assignResidueTypeBonds: don't copy bonds to atoms not in residue

src/proxy/atom-proxy.ts, src/store/residue-type.ts
My code for finding a reference atom in order to determine the offset vector for multiple bonds had a bug and was sometimes picking the wrong reference atom. This resulted in drawing ring double bonds on the outside of the ring on occasion.
Specificaly: If you have a biphenyl or similar system (single bond between two non-fused rings) then when trying to draw a double bond between ipso and ortho positions it might take the atom in the other ring as an acceptable reference atom. This PR also changes the `RingData` interface but I've checked the various locations this is used and don't think this causes any other problems
=> Update ring reference bond algorithm

examples/scripts/parser/pqr-explicit-radii.js, src/color/electrostatic-colormaker.ts, src/parser/pdb-parser.ts, src/proxy/atom-proxy.ts, src/representation/molecularsurface-representation.ts, src/representation/surface-representation.ts, src/surface/molecular-surface.ts, src/utils/radius-factory.ts
This adds a radiusType of 'explicit' plus the mechanism to get them from the file. Currently I think only the pqr parser provides explicit radii. 
I've also modified the electrostatic colormaker to use the partial charges (if present) so you get examples like this:
http://fredludlow.com/ngl/pqr-surface/examples/webapp.html?script=parser/pqr-explicit-radii
which are similar to the (very) approximate electrostatic surface we already had, but now you can use externally provided charges (e.g. from a forcefield).
That example also has a spacefill representation where radii are taken from pqr radii column (again via radiusType: 'explicit'). 
I've put the example under 'parser', but maybe it should be somewhere else?
=> 'explicit' radiusType, for surfaces/spacefill etc

src/viewer/viewer.ts
This is something I've been playing with here, and found it quite useful for easier picking of single-pixel line representations.  Basically it looks in a 5*5 rectangle of pixels centred on the pick event (starting at the middle and working outwards). 
If you compare picking in the line+cross representation example between this and the standard app you can see what I mean:
http://fredludlow.com/ngl/pick-wider/examples/webapp.html?script=representation/line-and-cross
If you think it would be better controlled by a parameter I can add that (stage.pickRadius?).
Fred
=> Look at neighbouring pixels when picking

src/structure/structure-constants.ts
This PR addresses the problem of hydrogen atoms from DNA or RNA ribose not identified as backbone atoms.
=> Add Hydrogen atoms to nucleic backbone atoms

src/parser/xplor-parser.ts
I think this fixes bug originally reported in arose/nglview#761. As @shallerdavid suggested - it didn't handle files where the dimension of the map xy-sections was not a multiple of 6.
=> Fix bug in xplor/cns parser, see #602

src/surface/marching-cubes.ts
Deep in the marching cubes algorithm, when interpolating between grid points and generating a new vertex, that vertex gets cached/looked up (as you'll be generating the same point when processing multiple cubes). However, the vertex is stored based only on the origin grid point not "gridpoint plus direction", so some vertices are in the wrong place and some triangles end up having duplicate vertices (i.e. the vetex indices of a triangle might be 1,1 and 2)
I fixed this for contoured surfaces some time ago, but for some reason didn't apply the fix to solid/wireframe surfaces, I guess I thought it required a larger array and I couldn't actually see anything wrong visually with the old version. Anyway - I've now found some examples where this is really definitely wrong - this simplifies the …
=> Marching-cubes bug

src/structure/structure-utils.ts
There's a call to `ResidueType.getBondIndex` that uses the atomID from the structure (including the offset) as opposed to the appropriate one for the ResidueType
=> Bug in calculateBondsWithin

src/geometry/grid.ts, src/surface/av-surface.ts, src/surface/edt-surface.ts
This fixes #594 for me (@xrobin could you see if it works for you?). `Grid` and `AVHash` are replaced with factory functions. This maintains the closure-style definition (rather than creating a class and setting prototype methods) which I think we found was helpful for performance back when adding the AVSurface code. That said, I don't have any benchmarks to back that statement up.
=> Change Grid and AVHash to factory functions to fix #594

src/stage/stage.ts, src/ui/parameters.ts, src/viewer/viewer.ts
This can be useful if NGL is embedded and additional graphics objects
are added to the stage outside NGL. Without expanding the bounding
box, those additional objects may be clipped or fogged.
(This is a repost of my old PR, with improved name.)
=> Add expandBoundingBoxFactor method to stage

src/buffer/buffer.ts
The groups' children refer back to the mesh, and the picking object
has a circular structure.data attribute.
I don't believe the groups or picking are required for
serialization (e.g. model export) so this change shouldn't impact
normal use.
=> Add toJSON to buffer.ts to avoid circular refs when exporting

src/geometry/spatial-hash.ts, src/surface/av-surface.ts
I found that some atoms were being returned multiple times from the spatial hash as the upper x,y,z limits were off by one when iterating over buckets. I don't think this would affect surfaces (degenerate atoms don't matter though they might slow it down a bit) but it does effect electrostatic coloring using atomic partial charges - contributions from one atom get applied multiple times. 
This moves the padding to the right place (I think!) - certainly it fixes both my coloring bug and hasn't broken any surface generation that I've tried.
=> Fix bounds for bucket iteration in spatial hash

src/geometry/spatial-hash.ts
There are a few instances in the code of something like `new SpatialHash(positions: Positions)` where `positions` is an `AtomStore` instance. The `SpatialHash` code looks at the length of `positions.x` to deduce number of atoms/positions, but this isn't necessarily correct (`Store.growIfFull` grows by 50% each time) so you can end up with a load of points in the hash at (0,0,0). This in turn screws up the bond perception (if you have an atom that is within covalent distance of the origin you build a load of bonds to non-existent atoms).
My change adds an optional `count` attribute to `Positions` type, which takes priority over `position.x.length` if present
=> Add optional count to SpatialHash positions argument

src/ngl.ts
I'm embedding NGL in a Typescript app, and noticed Component and StructureComponent aren't exported. This PR exports those, and related classes. This PR isn't terribly useful until @ppillot 's PR #524 is merged, but with those two together I'm able to build with typescript.
If there are more like this that should be included, I'm happy to revise this PR to include them.
=> Export typescript decls for Components

src/store/residue-type.ts, src/structure/structure-constants.ts
This branch fixes #650 
It adds a check for hetero value in the `isDna()` and `isRna()` methods before testing for specific atoms value such as O3' (which are also present in disaccharides).
It contains also a second commit for adding I and DI as base names in conformity with what Jmol does.
=> Fix nucleic saccharide

examples/js/gui.js
Otherwise:
PS: May be this happens due to adding new camera stereo type?
=> FIX fullscreen icon

src/buffer/doublesided-buffer.ts
Same fix as #609, applied to DoubleSidedBuffer since that does not extend Buffer.
I actually don't know if _any_ of this three.js userData is useful when exporting/serializing, but seems better to be safe and export whatever might be useful.
=> Avoid more circular refs when exporting

src/polyfills.js
When importing `ngl` for a Gatsby project, the build fails during server-side rendering:
```
12:29:17 PM: failed Building static HTML for pages - 4.560s
12:29:17 PM: error "window" is not available during server side rendering.
12:29:17 PM:   32 | }
12:29:17 PM:   33 |
12:29:17 PM: > 34 | if (typeof window.HTMLCanvasElement !== 'undefined' && !window.HTMLCanvasElement.prototype.toBlob) {
12:29:17 PM:      | ^
12:29:17 PM:   35 |   // http://code.google.com/p/chromium/issues/detail?id=67587#57
12:29:17 PM:   36 |   Object.defineProperty(window.HTMLCanvasElement.prototype, 'toBlob', {
12:29:17 PM:   37 |
12:29:17 PM: 
12:29:17 PM:   WebpackError: ReferenceError: window is not defined
12:29:17 PM:   
12:29:17 PM:   - ngl.esm.js:34 Module../node_modules/ngl/dist/ngl.esm.js
12:29:17 PM: …
```
=> Add check for window in polyfills

src/chemistry/interactions/contact.ts, src/component/structure-component.ts, src/representation/contact-representation.ts, src/representation/label-representation.ts, src/representation/representation.ts
This PR improves typings for representations: adds missing typings for some representations (points, dots, molecular surface,...) and handle the polymorphism of `filterSele` in contact representations (either string or string 2-tuple).
=> Representations typings

examples/scripts/test/clipping-absolute.js, examples/scripts/test/clipping-camera.js, src/controls/mouse-actions.ts, src/stage/stage.ts, src/ui/parameters.ts, src/viewer/viewer.ts
See #671 and #656 
As discussed, this ensures focusScroll behaves sensibly for both relative and absolute clipScale.
@garyo  I'd be grateful for any feedback on this one. One significant change I made was removing the fogMode and fogScale parameters (they now just follow clipMode and clipScale). I thought it made the logic quite complex for what I think would be a very unusual use case (i.e. camera clipping, scene fogging)?
=> Consistent focusScroll behaviour between relative/absolute clipping

src/representation/measurement-representation.ts
This fixes a bug where a new colour can't be set for measure labels
via `repr.setParameter({labelColor: 0xff0000})` but always defaults
to black instead.
This can be tested in the webapp with the distance representation example.
=> Force rebuild repr. after label color change

package-lock.json, package.json, src/buffer/buffer.ts, src/buffer/image-buffer.ts, src/parser/obj-parser.ts, src/stage/mouse-observer.ts, src/viewer/viewer.ts, tsconfig.json
* Fix mouse-wheel zoom direction
* Replace deprecated geometry `.addAttribute` calls (deprecated in three.js r110)
The mouse-wheel zoom fix might be overcomplicated but I did try to handle all cases.
=> Fixes for recent three.js r111 update

package-lock.json, package.json, src/buffer/buffer.ts, src/buffer/image-buffer.ts, src/parser/obj-parser.ts, src/representation/molecularsurface-representation.ts, src/stage/mouse-observer.ts, src/viewer/viewer.ts, tsconfig.json
This patch tries not to double the amount of geometry created by NGL in surface mode; currently it always creates a `DoubleSidedBuffer` even if the "side" param is not "double". This patch makes it only create the `DoubleSidedBuffer` when requested.
One thing I've noticed is that changing the "side" param does not regenerate the geometry; seems like (at least with this patch) it should. @arose if you could take a look at this I'd appreciate it.
=> In MolecularSurfaceRepresentation, create a double sided surface only when needed

src/structure/structure-constants.ts
Fixes the bug reported in arose/ngl#742
Technically only one of OT1 and OT2 is backbone but the labels are essentially arbitrary so I've added both.
=> Adding OT1 and OT2 to the list of valid backbone Oxygen identifiers.

src/component/structure-component.ts
Before this, `measureUpdate` would always pass `radiusData` to `setParameters`,
which would rebuild because it only checks for undefined.
This commit avoids calling `spacefillRepresentation.setParameters` if there's nothing to do, which
should speed up frame rate in some cases.
=> Avoid extra rebuilds on param changes when nothing is picked

examples/scripts/test/matrix.js, src/component/component.ts, src/component/structure-component.ts, src/controls/picking-proxy.ts, src/proxy/atom-proxy.ts, src/representation/contact-representation.ts, src/representation/representation.ts, src/representation/surface-representation.ts
This fixes a few bugs when a matrix is used to transform a component (component.setTransform(m: Matrix4)).
Specifically:
In picking-proxy, when trying to detect which atom is closer to the picked point (converting 3D coords to 2D screen position), the component matrix is not applied.
StructureComponent has a few special representations (for picking/measurements), these are now transformed as well
When using labels in ContactRepresentation, the generated TextBuffer was not being passed a full set of parameters.
=> Fix picking, measurements and contact labels when using component.setTransform

src/viewer/viewer.ts
Almost a one-character change (Fixes #779)
@garyo, I don't think this would have any consequences for your camera changes (unless you read orthographic.camera.zoom?)
=> Fix negative zoom in orthographic camera

src/parser/sdf-parser.ts
This PR fixes the regexp used for parsing extra data in SDF files.
According to [SDF spec showed in Wikipedia](https://en.wikipedia.org/wiki/Chemical_table_file#SDF),  extra data items in SDF files are denoted as follows.
The number of spaces between `>` and `<` is 2.
```
>  <Unique_ID>
XCA3464366
>  <ClogP>
5.825
>  <Vendor>
Sigma
>  <Molecular Weight>
499.611
```
However, [the current regexp that is used to search for metadata (`/> <(.+)>/`)](https://github.com/nglviewer/ngl/blob/v2.0.0-dev.37/src/parser/sdf-parser.ts#L11) contains only 1 space between `>` and `<`.
Therefore, I fixed the regexp to match the above example too.
=> Fix regexp for SDF extra data

src/math/vector-utils.ts
There's no "right" answer for what to do when normalizing a (0,0,0)
vector, but NaNs is definitely not a good result. This just leaves
the vector as (0,0,0), non-normalized but numerically valid.
Zero-length vectors can result from creating normals when building
isosurfaces, when a triangle is zero area.
I ran across this with a SARS-Cov2 model, making a vws surface. I think
it creates a zero-area triangle which triggers these NaNs in the triangle 
normals and positions. You don't notice them normally when just
viewing the results (three.js seems to be fairly forgiving, but I export
glTFs and they are fatal there.
=> Avoid divide-by-zero when normalizing vectors

src/math/vector-utils.ts
Same idea as b8d859a4. Just return the original vector if length is zero.
I added `length2` (length squared) to avoid computing an extra sqrt if length is zero.
=> Avoid divide-by-zero in v3normalize

examples/scripts/selection/hydrogen.js, src/proxy/atom-proxy.ts, src/selection/selection-constants.ts, src/selection/selection-parser.ts, src/selection/selection-test.ts
This adds two new selection keywords "polarh" and "apolarh" to display polar (-X-H) and non-polar (-C-H) hydrogen atoms.
=> added polarh and apolarh selection keywords

src/loader/parser-loader.ts
The showcase/qmean example was broken (it uses a 'csv' file with space delimiter, and the relevant `delimiter` parameter was not making it all the way to the CsvParser constructor). This is now fixed. The way this is done isn't totally satisfactory (we're telling ParserLoader the names of all possible parser parameters - would make sense to just tell it those that don't need to get passed through), I'll open an issue to make this more sensible, but right now this fixes that example.
Relates tangentially to #823, I'll comment there
=> Ensure CSV parameters are not dropped when creating the CsvParser

src/structure/structure-utils.ts
As per the title - fix the check for first char of atomname is integer in the `guessElement` function.
=> Correctly parse atomname of form '0C21', fixes #797

src/structure/structure.ts, src/writer/pdb-writer.ts
Allows partial structures to be written (by passing the appropriate `StructureView` object to PdbWriter as opposed to a `Structure` object).
e.g, given a structure `struc` you can write the data for atoms '1-10':
```javascript
var sv = struc.getView(new NGL.Selection('1-10'))
var writer = new NGL.PdbWriter(sv)
writer.getData() // Text for atoms in residues 1-10
```
=> Enables writing partial structures (for PDB format) as requested in #838

src/utils/label-factory.ts
Logs a useful error message to the console when your `labelFormat` string is broken, rather than just failing
=> Catch errors in sprintf

examples/scripts/interactive/callback-trajectory.js, src/trajectory/callback-trajectory.ts, src/trajectory/trajectory-utils.ts
This PR adds a new trajectory type that gets the frame count and individual frames from a callback function. This functions like `RemoteTrajectory` but leaves details of the request mechanism up to the callback function. 
In order to request the frame count the function is called with a single argument which is a callback that accepts the frame count as its first argument.
To request an individual frame the function is called  with a callback, the frame number and the atom indices. The callback takes 4 arguments which are the frame number, the box, the frame coordinates, and an updated frame count. 
Both of these requests mirror the behavior of the http requests of `RemoteTrajectory`.
We use ngl extensively in our cando-jupyter kernel. In the past we have reused the front end code of …
=> Add CallbackTrajectory

src/stage/stage.ts
This just updates a couple of defaults to be slightly nicer -- the default surface resolution is very low, which is good for performance, but I think modern systems can easily handle more triangles so why not make it look better by default? 
And it seems to me like a zero-offset van der Waals surface is a better surface default than the current 1.4Å-offset surface-accessible surface, but I'm happy to remove that if people prefer the current one.
=> Update defaults: set surface type to vws, increase surface resolution

src/buffer/buffer.ts
In this case, instead of creating a new `index` attribute array, it reuses the old one, which is fine, but it didn't reset the `count`, which could cause the old triangles to be reused, causing graphics glitches. Simple fix (but it took me a long time to find it!)
=> Fix volume surface gen when changing isolevel so geometry gets smaller

src/ngl.ts
`StructureRepresentationType` was exported, but `VolumeRepresentationType` was missing.
=> Export type VolumeRepresentationType

src/color/atomindex-colormaker.ts, src/color/bfactor-colormaker.ts, src/color/chainid-colormaker.ts, src/color/chainindex-colormaker.ts, src/color/chainname-colormaker.ts, src/color/colormaker.ts, src/color/densityfit-colormaker.ts, src/color/electrostatic-colormaker.ts, src/color/element-colormaker.ts, src/color/entityindex-colormaker.ts, src/color/entitytype-colormaker.ts, src/color/geoquality-colormaker.ts, src/color/hydrophobicity-colormaker.ts, src/color/modelindex-colormaker.ts, src/color/moleculetype-colormaker.ts, src/color/occupancy-colormaker.ts, src/color/partialcharge-colormaker.ts, src/color/random-colormaker.ts, src/color/randomcoilindex-colormaker.ts, src/color/residueindex-colormaker.ts, src/color/resname-colormaker.ts, src/color/selection-colormaker.ts, src/color/sstruc-colormaker.ts, src/color/uniform-colormaker.ts, src/color/value-colormaker.ts, src/color/volume-colormaker.ts, src/representation/representation.ts, src/stage/stage.ts, src/viewer/viewer.ts, tsconfig.json
Here's my color-management code -- linear workflow internally, turned on by default.
I've been using it for a while and it works well for me. There are two issues to discuss, I think:
1. How to allow users to specify the color encoding, if they want to go back to the default? I've added a `colorEncoding` param to the viewer, which seems like a good place for it, but I don't have a good idea on how to thread it through to colormaker.ts where it's needed. So right now that param does nothing -- in order to get back to the old workflow you have to change `colorSpace` in colormaker.ts. Ideas appreciated.
2. @arose commented in #775 that it might be better to implement color management in the shader; I'd like to propose that it's at least OK if not better to do it this way because the values …
=> Color management: linear workflow

examples/scripts/interactive/crosslinking.js
Currently the interactive/crosslinking example codesandbox is a blank screen
It has nested double quotes in a string, which is a syntax error. This PR proposes changing it to use a template string
Not clear why it was changed to double strings in the code sandbox or why it didn't escape the double quotes, but I thought using template strings may be a workaround
=> Possible fix for interactive/crosslinking example on sandbox

package-lock.json, package.json, rollup.config.dist.js, rollup.config.js
I've tried to do a bit of cleanup of the dependencies and build process, some of this is uncontroversial bumping versions / removing deprecated plugins, and some of it changes build behaviour a bit, so please comment if you have a view!
I've updated the deprecated rollup plugins (typescript, buble etc).
The build-min job has changed quite a lot, it used to take the uncompressed dev build form the build/ folder and run it through uglify-js to create dist/ngl.js. It would also copy the esm and umd modules to dist too. 
I now use rollup with rollup-plugin-tersify (removing uglify-js dependency) so the minified versions are built in a rollup job from the source .ts files. The main advantage of this is that correct sourceMaps can be generated for the minified files. **I have also changed the …
=> Housekeeping

src/stage/mouse-observer.ts, src/stage/stage.ts, src/viewer/viewer.ts
I realised that there were some functions still being called recursively at every frame even after removing the scene.
In hope of getting rid of as much as I could, I was removing everything by doing:
```js
stage.removeAllComponents();
stage.dispose();
stage.viewer.container.innerHTML = "";
stage = null;
```
This might not be too much of a problem in some pages, but if you happen to add and remove stages a lot (popup/modal with ngl viewer, or single-page applications) then this can build up.
After adding and removing a stage 20 times (using a modified version of `/examples/embedded.html`) This is what I would get on the performance tab of Chrome.
Every single frame I would have 20 calls to `mouseObserver._listen()` and 20 to `viewer.animate()` that would amount to about 5ms of useless use …
=> performance optimisation when stage has been disposed of

src/stage/mouse-observer.ts
The current behavior in `MouseObserver#_setCanvasPosition` prefers offsetX/offsetY instead of the calculation using clientX/clientY as the latter did not work in Safari (https://github.com/nglviewer/ngl/commit/fd97378a3e966724fb8049a5064fc39134997f03). Presumably this is due to Safari's [lack of support of clientX/clientY on touch events](https://caniuse.com/mdn-api_touch_clientx).
In my use case, I am using NGL in an offscreen canvas, rendering the result to a separate canvas I already have for my application, and then forwarding events from my canvas to NGL. However, for some reason (which I don't completely understand, though likely a browser bug or undefined behavior) when I create a synthetic mouse event in Firefox, the offsetX and offsetY are set to 0 (in Chrome, both values are …
=> Fix hovering behavior when using synthetic events in Firefox

src/color/colormaker.ts
Very small change. Previously, if colorDomain and colorReverse were set, the colorDomain array would be reversed in place (in the colormaker's scale creation step). If the representation requires multiple instances of colormaker (e.g. ball+stick) then theeven numbered ones appear with the color reversed:
https://codepen.io/fludlow/pen/KKXjRwY
This fix copies the array before reversing it (so the original one isn't mutated)
=> Don't mutate colorDomain in place when colorReverse is true

src/parser/cif-parser.ts
Per https://mmcif.wwpdb.org/dictionaries/mmcif_pdbx_v50.dic/Items/_atom_site.auth_seq_id.html, auth_seq_id is an alternative numbering to match a publication, whereas label_seq_id is a sequential identifier. It is possible to have CIF files with the latter, but not the former (in my case, the file I was using was created by extracting the chain chain LB from PDB 3J9Z in PyMOL, then exported to CIF).
Related: #696
=> Use label_seq_id if auth_seq_id is not present in CIF

src/viewer/viewer.ts
In my app, I've integrated rendering using EffectComposer, including an OutlinePass. The OutlinePass relies on rendering with special materials, which are not `ShaderMaterial`s and as such do not have the uniforms property.
Let me know if there's a better way to handle this (and if I should change the type of `material` to `Material`)
=> Fix crash when using alternate materials (eg when using outline effect)

package-lock.json, package.json, rollup.config.dist.js
This reduces the bundle size by a few hundred kb. I added the bundle both as ESM and UMD.
It would be nice if ngl itself could be treeshaken, e.g., the parsers and representations are quite large.
=> Enable three.js treeshaking with three-minifier-rollup

src/representation/structure-representation.ts
This is a fix for a regression introduced in 3405abbd0a8ec1de35aa63d0e90126beb5d07b44.
I went through the code and noticed that in commit 3405abbd0a8ec1de35aa63d0e90126beb5d07b44 the file [`structure-representation.ts`](https://github.com/nglviewer/ngl/commit/3405abbd0a8ec1de35aa63d0e90126beb5d07b44#diff-09bd4aa7341d7b6b788671287da35019dd485d4d6849f6eb0c91da2553523bf1) was changed. Even though the commit was supposed to only update new Typescript rules it changed behaviour, causing the bug.
---
When updating `ngl` in our project from `2.0.0-dev.39` to `2.0.0-dev.40` I noticed that adding new representations after removing old ones didn't work anymore. The old representations were simply removed and new ones didn't appear in the viewer.
It is working as expected in version `2.0.0-dev.39` …
=> fix: don't dispose structure

src/parser/sdf-parser.ts
The atomTypeId array in AtomStore is currently an array of 16 unsigned integers. This causes problems when loading an SDF file with more than 64k atoms. The atomTypeId overflows at this point and the bonds begin to refer to the wrong atoms. For example a bond between atom 65535 and atom 65537 will turn into a bond between atom 65535 and atom 1.
=> Make atom names unique only within a model for SDF

src/buffer/cylinder-buffer.ts, src/buffer/hyperballstick-buffer.ts, src/buffer/sphere-buffer.ts
This PR allows instances of CylinderBuffer to be properly be typed as a `CylinderGeometryBuffer | CylinderImpostorBuffer`, as that's what the constructor returns.
FWIW: I'm not a fan of the `as any` casting as it avoids proper type checking. It might be preferable to change the API here to be a static method instead.
=> Improve typing of "impostorable" buffers

.gitignore, src/buffer/buffer.ts, src/buffer/cylinder-buffer.ts, src/buffer/cylindergeometry-buffer.ts, src/buffer/cylinderimpostor-buffer.ts, src/buffer/hyperballstick-buffer.ts, src/buffer/hyperballstickimpostor-buffer.ts, src/buffer/point-buffer.ts, src/buffer/sphere-buffer.ts, src/buffer/spheregeometry-buffer.ts, src/buffer/text-buffer.ts, src/buffer/tubemesh-buffer.ts, src/buffer/vector-buffer.ts, src/buffer/wideline-buffer.ts, src/color/colormaker.ts, src/component/representation-collection.ts, src/component/structure-component.ts, src/globals.ts, src/loader/loader-utils.ts, src/loader/loader.ts, src/representation/label-representation.ts, src/representation/measurement-representation.ts, src/representation/representation.ts, src/stage/stage.ts, src/structure/structure.ts, src/types.ts
This PR contains a new round about Typescript declarations.
1. Currently declarations are not shipped via npm: the user still has to make the compilation locally to get the files. This is due to a line in git ignore which prevents committing the declaration folder located in ./dist/
2. Various improvements to declarations, mainly function parameters which had been wrongly typed previously. This collection of fixes comes from unwarranted typescript errors that were raised in a project I am working on. Notably: `color` parameter can be a string (was limited to numbers), `autoview()` can take a selection string as a parameter, `labelText` takes an array of strings,...
=> Ts declarations

src/structure/structure-utils.ts, test/structure/tests-structure-utils.spec.ts
A bug was visible after loading a parm7 (Amber topology file) file where a ligand contains a chlorine with an atom name like `CL1`.
When parsing parm7 files, NGL infers the element from the atom name using the `guessElement()` utility function.
In this function there was a limitation to atom name processing where digits were stripped from the left only, and up to 2 digits.
This PR contains a change to find the first group of letters in the atom name with minimal processing (no regexp, no `parseInt`, only one call to `.substring()` at most)
It also adds to the logic of element identification by recognizing 2-letters standard elements names such as `Mg`
It was impractical to share the parm7 file where the bug was detected but a series of tests has been added to assess the guessElement …
=> Fix parm7 parsing: guessElement for CL1 returns carbon

.github/workflows/node.js.yml
This updates the node versions for CI (removes v12, adds v18) and updates some of the dependent actions to latest versions which squashes a lot of warnings about deprecated calls to save-state and similar
=> Actions housekeeping

src/component/structure-component.ts, src/structure/structure.ts, test/structure/tests-structure.spec.ts
NGL supports updating atomic coordinates (there's an updatePosition method on structure, and the trajectory viewer works this way). Currently however, there's not really a consistent way to listen for coordinate changes. A `StructureComponent` can have a trajectory, and listens for `frameChanged` to updates representations.
This is problematic when you have multiple parts of your app that might update coordinates, but all of which need to know when coordinates change.
This PR assumes `Structure.updatePosition` is the public API for updating atomic coordinates. This method has a new `refresh` parameter (default true, set to false for old behaviour) which will call `Structure.refreshPosition`, this recalculates bounding boxes etc and fires the `refreshed` signal which triggers …
=> Proposal - changing structure.refreshed signal and logic

src/representation/representation.ts
Some representation types (label) specifically set their parameters like 'linewidth' to null (e.g [here](https://github.com/nglviewer/ngl/blob/83cea2007c27222f79f9cbf9dd699866383255d1/src/representation/label-representation.ts#L220)) . If you try to setParameters({linewidth: 1.5}) this would attempt to access attributes on null in the Representation `setParameters` method [here](https://github.com/nglviewer/ngl/blob/83cea2007c27222f79f9cbf9dd699866383255d1/src/representation/representation.ts#L591). 
This one char fix avoids throwing an error (though obviously setting linewidth:1.5 on a label representation is meaningless anyway, but unhandled exceptions are bad).
=> Broaden undefined check when applying representation parameters.

src/parser/cif-parser.ts
Resolves #980. AlphaFold-DB structures in .cif format seem to miss `pdbx_PDB_helix_class` values, which causes an error. The introduced check prevents this issue. Example:
https://alphafold.ebi.ac.uk/files/AF-Q5VSL9-F1-model_v4.cif
How to reproduce:
```html
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<title>Title</title>
<script src="build/js/ngl.dev.js"></script>
</head>
<body>
<div id="viewport" style="width:400px; height:400px; "></div>
<script>
new NGL.Stage("viewport", {backgroundColor: 'grey'}).loadFile(
'https://alphafold.ebi.ac.uk/files/AF-Q5VSL9-F1-model_v4.cif'
).then(structure => {
structure.addRepresentation("cartoon");
structure.autoView();
}
).catch(alert);
</script>
</body>
</html>
```
Before the change, this code snippet should throw an error, because …
=> Check for missing `pdbx_PDB_helix_class` in CifParser

src/controls/mouse-actions.ts
Both scroll and drag-shift-right do focusScroll action in pymol, but scroll is more intuitive, because this makes controls mouse-only.
=> added scroll for focusScroll in pymol mouse controls

src/loader/parser-loader.ts, src/parser/cif-parser.ts, src/parser/gro-parser.ts, src/parser/mol2-parser.ts, src/parser/parser.ts, src/parser/pdb-parser.ts, src/parser/prmtop-parser.ts, src/parser/psf-parser.ts, src/parser/sdf-parser.ts, src/parser/structure-parser.ts, src/parser/top-parser.ts, src/structure/structure-utils.ts
For some PDB format files, I am seeing extra bonds drawn between atoms when they are within what would normally be considered covalent range but not actually bonded (I'm trying to find some good CSD examples I can share and will update with an appropriate test case). The current rules for detecting bonds use sum of some preset covalent radii and a threshold, but some of these structures legitimately fall within this threshold, though there is no bond.
This PR adds an `inferBonds` parameter when loading a structure, currently only consumed by the PDB parser class. It's behaviour is:
* `all` - Default, existing behaviour - creates bonds between any atoms within in a residue according to distance rules
* `auto` - For a het group residue (and only het groups), if any bonds are specified (by …
=> Infer bond options

src/parser/cif-parser.ts
This PR fixes 2 bugs in relation with CIF files parsing:
- #999 chem_comp can be set for macromolecular cif files and contain vectors of entities. In the case of mmCIF files the block of code that parses files containing only one entity (such as PDB het cif files) must not be reached.
- #950 core cif files often define charges as part of the atom type symbol. In that case, the element symbol must be stripped of the charge.
=> #999 cif parsing

src/color/colormaker-registry.ts, src/color/colormaker.ts
This PR fixes issue #1010 where the syntax for registering a ColorMaker does not generate valid JS.
After bissection, I've found out that this issue has been introduced with the recent changes to the build process (PR #993). It's possible that the transpilation + bundling results in invalid JS code (?).
The fix was already done in the update-three,js ongoing branch, and had been cherry-picked from there.
=> #1010 Colormaker-constructor

src/datasource/pdbe-datasource.ts, src/datasource/rcsb-datasource.ts
This PR fixes 2 issues:
- mmtf format is not supported by data providers (RCSB and PDBe)
- RCSB redirects from http to https but this can't be followed by the request code. Calls are now only made to https
=> Rcsb provider fixes

src/ngl.ts, src/parser/ply-parser.ts
This seems to work... (TS conversion of the latest PLYLoader from the three.js project and adaptation into the NGL parser infrastructure)
The parser/ply example is active again.
Fixes #1049
=> Reinstate the PLY parser
