js/ngl/writer.js

renumberSerial option previously not activated

FIX: renumberSerial activated

---

src/proxy/bond-proxy.js
src/store/residue-type.js

Fixes reference atom detection

---

src/surface/av-surface.js
src/surface/molecular-surface.js

Newer, faster version, see #209 and #205

Improved performance of AVSurface (added AVHash class)

---

examples/js/examples.js
src/buffer/contour-buffer.js
src/representation/molecularsurface-representation.js
src/surface/av-surface.js
src/surface/edt-surface.js
src/surface/marching-cubes.js
src/surface/molecular-surface.js
src/surface/surface.js
src/surface/volume.js

Hopefully ready now! (see #198)
I was about to send a PR with the `edgeFilter` bits removed and a comment on how there were still occasional holes in the surface, turns out I'd made a big error in how I loop over triangles (see 63c1bb0). This version has hole-free surfaces (I hope) and I've reinstated `edgeFilter` to reduce unnecessary duplicated lines (which might make a small difference on huge surfaces)

Contoured Surfaces

---

src/streamer/network-streamer.js

NetStreamer bug fixes

---

src/controls/viewer-controls.js

Bugfix for arose/ngl#261 - orthographic camera zoom broken

---

src/controls/trackball-controls.js
src/stage/stage.js

I wrote this to fix #275, then saw your commit 8de48d4. You might prefer to rewrite rather than merge, but have a PR anyway and merge/close as you see fit!

Sync mouse movement with translation

---

src/representation/hyperball-representation.js

Continuing a great tradition of 1 and 2 character PRs :)

fix typo: radius1 -> radius

---

src/writer/pdb-writer.js

A trivial 2 characters change PR

Pdb writer patch

---

examples/js/gui.js

supported formats by MDsrv, internal handling by mdanalysis & mdtraj

update supported remote trajectories (remoteTrajExt)

---

examples/scripts/representation/line-and-cross.js
src/representation/line-representation.js

References: #354. Let me know if there's anything else that needs adding or fixing.

Add cross depiction to LineRepresentation

---

examples/js/gui.js

structure file path available with trajectory file for other tools (mdsrv) via GET request
(solving issue #372 )

structure path availability

---

src/parser/mmtf-parser.js

Replaces unit8 with int8 for storing formalcharge in mmtf parser

MMTF formal charge as signed int

---

src/controls/mouse-actions.ts

Because it's what my users are used to. Hope that's okay!

Added astexviewer mouse preset

---

src/representation/dihedral-representation.js

Sorry, should have sent this last week (see #417). Renders extra lines as shown by @arose's screenshot
https://github.com/arose/ngl/issues/417#issuecomment-346454294
If you've manually merged/pulled already then please close

Additional lines in dihedral repr

---

examples/scripts/representation/label.js
package.json
src/representation/label-representation.js
src/utils/label-factory.ts

See #391. Updated the representation/label example to use a custom format.

Sprintf labels

---

src/stage/stage.ts
src/viewer/viewer.ts

Revert " fix: relative css position for preventing bug in annotations #461"

---

src/geometry/helixbundle.ts
src/geometry/helixorient.ts

Starting to introduce myself with the code base, and helping out the TypeScript conversion effort!

Updating helix geometry classes

---

src/ngl.ts
src/parser/kin-parser.js

Added parsing of balllists and ribbonlists to kinparser.
Added parsing of additional point and list kin keywords.
Added access to MeshBuffer to ngl.ts to be used with kin ribbonlists.

Additional features to kinparser

---

src/controls/key-controls.ts
src/stage/key-behavior.ts

change keycontrols to work with event.key

---

src/chemistry/interactions/contact.ts
src/chemistry/interactions/hydrogen-bonds.ts
src/math/array-utils.ts
src/representation/contact-representation.ts

As the title really! Adds labelVisible, labelFixedSize, labelSize and labelUnit to contacts. 
I had to make a few changes elsewhere to keep the TS compiler happy, and I'm not sure I've necessarily done things the best way - I'm very open to suggestions (still a novice at TS)
Cheers, Fred

Add optional labels to contact representation

---

examples/scripts/color/electrostatic.js
src/color/electrostatic-colormaker.ts
src/surface/av-surface.ts

A few fixes for surfaces and electrostatic coloring
Specifically, fix the buggy surfaces seen at high scaleFactor values in 'av' mode, assign correct atom indices, and tidy up electrostatic coloring code.

Surface tweaks

---

src/viewer/tiled-renderer.ts

ok, following (sort of) fredludlows advice, I made a clean install of ngl and just changed/committed tiledrenderer.ts to avoid all the cruft that had accumulated in my version

tiledrenderer gap fix

---

package-lock.json
package.json

I thought I included this in the last PR but I missed it.

Fix build using new cpy (was broken in ece8274a)

---

README.md
src/component/component.ts

Should avoid possible new issues like #788

hint for setTransform for global rotation in setRotation doc

---

src/ngl.ts

There are certainly more that could be added but these are a start.

Add a few more typescript decls

---

src/color/atomindex-colormaker.ts
src/color/bfactor-colormaker.ts
src/color/chainid-colormaker.ts
src/color/chainindex-colormaker.ts
src/color/chainname-colormaker.ts
src/color/colormaker-registry.ts
src/color/densityfit-colormaker.ts
src/color/electrostatic-colormaker.ts
src/color/element-colormaker.ts
src/color/entityindex-colormaker.ts
src/color/entitytype-colormaker.ts
src/color/geoquality-colormaker.ts
src/color/hydrophobicity-colormaker.ts
src/color/modelindex-colormaker.ts
src/color/moleculetype-colormaker.ts
src/color/occupancy-colormaker.ts
src/color/partialcharge-colormaker.ts
src/color/random-colormaker.ts
src/color/randomcoilindex-colormaker.ts
src/color/residueindex-colormaker.ts
src/color/resname-colormaker.ts
src/color/selection-colormaker.ts
src/color/sstruc-colormaker.ts
src/color/uniform-colormaker.ts
src/color/value-colormaker.ts
src/color/volume-colormaker.ts
src/controls/mouse-controls.ts

Various typings fixes. No code change.

Typing-fixes

---

src/structure/structure-data.ts
src/structure/structure.ts
src/utils/picker.ts

This parameter is always set as a BondPicker, so I've typed it accordingly in order to make the relevant methods available

Update type of BondData#picking to the more correct BondPicker

---

.github/workflows/node.js.yml
package.json

I've added a basic Github Actions config to check out, build, test (should catch typescript issues). 
Will see if I can figure out releasing via pushing a tag or similar in a separate PR

Setup Github Actions
